### ISSUE TITLE
ESP32 Firmware Version

### ISSUE THREAD

**Issue by tardani95** [ETS-PoliTO/esp32-sniffer#4]
Hi,

I am curious which ESP-IDF did you use for this project?
According to the path settings from the usage section, in the readme, I assume that you are using version 3.2.

Could you please confirm that?

**Comment by J4NN0** [comment]
Hi Daniel,

I think so, at the moment I do not remember as I did it a couple of years ago. Anyway, I suggest you always use the last stable version (at the moment it should be the 4.2).
